# Generated by Django 5.2.8 on 2025-11-09 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Подробное описание инцидента', verbose_name='Описание проблемы')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В работе'), ('resolved', 'Решен'), ('closed', 'Закрыт'), ('cancelled', 'Отменен')], default='open', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(choices=[('operator', 'Оператор'), ('monitoring', 'Мониторинг'), ('partner', 'Партнер'), ('system', 'Система')], max_length=20, verbose_name='Источник')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
            ],
            options={
                'verbose_name': 'Инцидент',
                'verbose_name_plural': 'Инциденты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='incidents_i_status_9a4f12_idx'), models.Index(fields=['source'], name='incidents_i_source_0e027a_idx'), models.Index(fields=['created_at'], name='incidents_i_created_8be57d_idx')],
            },
        ),
    ]
